#! /usr/bin/env python

import yaml,logging
import sys,os
import numpy as np
#import wham
from txtreader import Txtreader
#from multiprocessing import Pool
#logging.basicConfig()
#logger.setLevel(logging.WARN)
#
logger = logging.getLogger(__name__)

class Reader1d():
  '''  Class for reading umbrella sampling input
  '''

  def __init__(self,infile='Proj.yaml'):

        
    if not os.path.isfile(infile):
        raise SystemExit("projectfile {0} not found ... Exiting !\n".format(infile))
    
    inpf=open(infile,'r')
    records=yaml.load(inpf)
    #print records
    self.trials=records['trials']
    self.systems=records['systems']    
    self.positions=records['positions']
    self.x0=records['x0']
    self.kx=records['kx']
    
    if len(self.x0) != len(self.kx):
        raise SystemExit("x0 {0} and kx {1} of different size".format(len(self.x0), len(self.kx))) 

    self.xvgsuffix=records['xvgsuffix']
    self.xtcsuffix=records['xtcsuffix']
    self.xvgdir=records['xvgdir']
    self.xtcdir=records['xtcdir']
    self.stride=records['stride']

    logger.info("%s file sucessfully loaded",infile)
    logger.info("positions: %d",len(self.positions))
    
    self.xvgfiles,self.xtcfiles = self._genxvgandxtcnames()
    logger.debug("first xvgfile: %s",self.xvgfiles[0])
    

  def read_xvgfiles(self,readupto=0,btime=False):
    ''' 
    Read umbrella output files generated by gromacs.
    Arguments:
        readupto: int 
            lines to read upto
        skipline: int
            skip every nth line
        btime: boolean
            whether to return time column
    Returns:
        pos_kn: 2D array, with each file enteries as row 
        N_k: Number of rows in each file
    '''
    trials=self.trials
    systems=self.systems
    positions=self.positions
      
    pos_kn=[]
    N_k=[]
    for infile in self.xvgfiles:
        if not os.path.isfile(infile):
            raise SystemExit("file {0} not found\n".format(infile))
    
        data=Txtreader(infile)
        data.readcols(readupto=readupto,skipline=self.stride)
        N_k.append(data.cols.shape[0])
        pos_kn.append(data.cols[:,:])
          
    N_k=np.array(N_k)
    N_max=N_k.max()
    logger.debug("N_max %d ",N_max)
    logger.debug("N_k %s",N_k )
    
    pos_kn1=np.zeros((len(pos_kn),N_max),dtype=np.float32)
    timestamp_kn = np.zeros((len(pos_kn),N_max),dtype=np.float32)
    
    # Only the last column is used as observations
    
    for i,d in enumerate(pos_kn):
        timestamp_kn[i,0:N_k[i]] = d[:,0]
        pos_kn1[i,0:N_k[i]]= d[:,-1]
         
    logger.debug("pos_kn.shape %s",pos_kn1.shape )
    
    if btime == False:
        return pos_kn1,N_k
    else:
       return pos_kn1,N_k,timestamp_kn
          

  def _genxvgandxtcnames(self):
    ''' Generate file names for xvg and xtc files 
    '''   
    xvgfiles = []
    xtcfiles = []   
    for trial in self.trials:
      for system in self.systems:
        for pos in self.positions:
            xvgfile=("%s/%s_%s_%s_%s.xvg"%(self.xvgdir,trial,system,
                                             pos,self.xvgsuffix))
            xtcfile=("%s/%s_%s_%s_%s.xtc"%(self.xtcdir,trial,system,
                                             pos,self.xtcsuffix))
            xvgfiles.append(xvgfile)
            xtcfiles.append(xtcfile)
            
    return xvgfiles,xtcfiles

          